<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOvrvmac\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOvrvmac/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOvrvmac.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOvrvmac\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOvrvmac\appProdProjectContainer([
    'container.build_hash' => 'Ovrvmac',
    'container.build_id' => '9847e4cf',
    'container.build_time' => 1587603709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOvrvmac');
